import { ASSET_CLASS_LABELS } from "./constants";
import type { AssetMetadata, AssetRegistry } from "./types";

export const assetRegistry: AssetRegistry = {
  // -------------------------
  // Crypto
  // -------------------------
  BTCUSDT: {
    symbol: "BTCUSDT",
    label: "Bitcoin",
    assetClass: "crypto",
    groupLabel: ASSET_CLASS_LABELS.crypto,
    marketDataProvider: "binance",
    providerSymbol: "BTCUSDT",
    pricePrecision: 2,
    order: 1,
    isDefault: true,
    tags: ["btc", "bitcoin", "major"],
  },
  ETHUSDT: {
    symbol: "ETHUSDT",
    label: "Ethereum",
    assetClass: "crypto",
    groupLabel: ASSET_CLASS_LABELS.crypto,
    marketDataProvider: "binance",
    providerSymbol: "ETHUSDT",
    pricePrecision: 2,
    order: 2,
    tags: ["eth", "ethereum", "major"],
  },
  SOLUSDT: {
    symbol: "SOLUSDT",
    label: "Solana",
    assetClass: "crypto",
    groupLabel: ASSET_CLASS_LABELS.crypto,
    marketDataProvider: "binance",
    providerSymbol: "SOLUSDT",
    pricePrecision: 3,
    order: 3,
    tags: ["sol", "solana"],
  },
  XRPUSDT: {
    symbol: "XRPUSDT",
    label: "XRP",
    assetClass: "crypto",
    groupLabel: ASSET_CLASS_LABELS.crypto,
    marketDataProvider: "binance",
    providerSymbol: "XRPUSDT",
    pricePrecision: 4,
    order: 4,
    tags: ["xrp"],
  },
  SUIUSDT: {
    symbol: "SUIUSDT",
    label: "Sui",
    assetClass: "crypto",
    groupLabel: ASSET_CLASS_LABELS.crypto,
    marketDataProvider: "binance",
    providerSymbol: "SUIUSDT",
    pricePrecision: 4,
    order: 5,
    tags: ["sui"],
  },

  // -------------------------
  // US Market
  // -------------------------
  QQQ: {
    symbol: "QQQ",
    label: "Invesco QQQ",
    assetClass: "us",
    groupLabel: ASSET_CLASS_LABELS.us,
    marketDataProvider: "yahoo",
    providerSymbol: "QQQ",
    pricePrecision: 2,
    order: 101,
    isDefault: true,
    tags: ["nasdaq", "etf"],
  },
  SPY: {
    symbol: "SPY",
    label: "SPDR S&P 500 ETF",
    assetClass: "us",
    groupLabel: ASSET_CLASS_LABELS.us,
    marketDataProvider: "yahoo",
    providerSymbol: "SPY",
    pricePrecision: 2,
    order: 102,
    tags: ["sp500", "etf"],
  },
  NVDA: {
    symbol: "NVDA",
    label: "NVIDIA",
    assetClass: "us",
    groupLabel: ASSET_CLASS_LABELS.us,
    marketDataProvider: "yahoo",
    providerSymbol: "NVDA",
    pricePrecision: 2,
    order: 103,
    tags: ["stock", "ai"],
  },
  AAPL: {
    symbol: "AAPL",
    label: "Apple",
    assetClass: "us",
    groupLabel: ASSET_CLASS_LABELS.us,
    marketDataProvider: "yahoo",
    providerSymbol: "AAPL",
    pricePrecision: 2,
    order: 104,
    tags: ["stock", "mega-cap"],
  },
  MSFT: {
    symbol: "MSFT",
    label: "Microsoft",
    assetClass: "us",
    groupLabel: ASSET_CLASS_LABELS.us,
    marketDataProvider: "yahoo",
    providerSymbol: "MSFT",
    pricePrecision: 2,
    order: 105,
    tags: ["stock", "mega-cap", "ai"],
  },

  // -------------------------
  // Korea Market
  // -------------------------
  KOSPI: {
    symbol: "KOSPI",
    label: "KOSPI",
    assetClass: "kr",
    groupLabel: ASSET_CLASS_LABELS.kr,
    marketDataProvider: "manual",
    providerSymbol: "KOSPI",
    pricePrecision: 2,
    order: 201,
    isDefault: true,
    tags: ["index", "korea"],
  },
  KOSDAQ: {
    symbol: "KOSDAQ",
    label: "KOSDAQ",
    assetClass: "kr",
    groupLabel: ASSET_CLASS_LABELS.kr,
    marketDataProvider: "manual",
    providerSymbol: "KOSDAQ",
    pricePrecision: 2,
    order: 202,
    tags: ["index", "korea"],
  },
  "005930": {
    symbol: "005930",
    label: "Samsung Electronics",
    assetClass: "kr",
    groupLabel: ASSET_CLASS_LABELS.kr,
    marketDataProvider: "manual",
    providerSymbol: "005930",
    pricePrecision: 0,
    order: 203,
    tags: ["stock", "korea", "samsung"],
  },
  "000660": {
    symbol: "000660",
    label: "SK Hynix",
    assetClass: "kr",
    groupLabel: ASSET_CLASS_LABELS.kr,
    marketDataProvider: "manual",
    providerSymbol: "000660",
    pricePrecision: 0,
    order: 204,
    tags: ["stock", "korea", "semiconductor"],
  },

  // -------------------------
  // Metals
  // -------------------------
  XAUUSD: {
    symbol: "XAUUSD",
    label: "Gold",
    assetClass: "metals",
    groupLabel: ASSET_CLASS_LABELS.metals,
    marketDataProvider: "manual",
    providerSymbol: "XAUUSD",
    pricePrecision: 2,
    order: 301,
    isDefault: true,
    tags: ["gold", "precious-metals"],
  },
  XAGUSD: {
    symbol: "XAGUSD",
    label: "Silver",
    assetClass: "metals",
    groupLabel: ASSET_CLASS_LABELS.metals,
    marketDataProvider: "manual",
    providerSymbol: "XAGUSD",
    pricePrecision: 3,
    order: 302,
    tags: ["silver", "precious-metals"],
  },

  // -------------------------
  // FX
  // -------------------------
  USDKRW: {
    symbol: "USDKRW",
    label: "USD/KRW",
    assetClass: "fx",
    groupLabel: ASSET_CLASS_LABELS.fx,
    marketDataProvider: "manual",
    providerSymbol: "USDKRW",
    pricePrecision: 2,
    order: 401,
    isDefault: true,
    tags: ["fx", "major", "korea"],
  },
  AUDUSD: {
    symbol: "AUDUSD",
    label: "AUD/USD",
    assetClass: "fx",
    groupLabel: ASSET_CLASS_LABELS.fx,
    marketDataProvider: "manual",
    providerSymbol: "AUDUSD",
    pricePrecision: 4,
    order: 402,
    tags: ["fx", "major", "australia"],
  },
  USDAUD: {
    symbol: "USDAUD",
    label: "USD/AUD",
    assetClass: "fx",
    groupLabel: ASSET_CLASS_LABELS.fx,
    marketDataProvider: "manual",
    providerSymbol: "USDAUD",
    pricePrecision: 4,
    order: 403,
    tags: ["fx", "major", "australia"],
  },
  USDJPY: {
    symbol: "USDJPY",
    label: "USD/JPY",
    assetClass: "fx",
    groupLabel: ASSET_CLASS_LABELS.fx,
    marketDataProvider: "manual",
    providerSymbol: "USDJPY",
    pricePrecision: 3,
    order: 404,
    tags: ["fx", "major", "japan"],
  },
};

export const assetList: AssetMetadata[] = Object.values(assetRegistry).sort(
  (a, b) => a.order - b.order,
);
